#!/usr/bin/env bash
set -e

# === helper ===
log() { printf "\n\033[1;32m[INFO]\033[0m %s\n" "$*"; }
warn() { printf "\n\033[1;33m[WARN]\033[0m %s\n" "$*"; }

if [[ "$OSTYPE" != "darwin"* ]]; then
  warn "This script is designed for macOS."
  exit 1
fi

# --- Homebrew ---
if ! command -v brew >/dev/null 2>&1; then
  log "Homebrew not found. Installing..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  if [[ -d /opt/homebrew ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
  elif [[ -d /usr/local/Homebrew ]]; then
    eval "$(/usr/local/Homebrew/bin/brew shellenv)"
  fi
else
  log "Homebrew already installed."
fi

# --- brew packages ---
log "Installing packages via Homebrew..."

brew update

brew tap homebrew/cask-fonts || true

brew install --cask iterm2
brew install --cask font-meslo-lg-nerd-font

brew install zsh tmux fzf ripgrep bat fd eza git
brew install romkatv/powerlevel10k/powerlevel10k
brew install zsh-autosuggestions zsh-syntax-highlighting zsh-history-substring-search

# --- iTerm2 Snazzy theme ---
log "Downloading and opening iTerm2 Snazzy theme..."
(curl -Ls https://raw.githubusercontent.com/sindresorhus/iterm2-snazzy/main/Snazzy.itermcolors > /tmp/Snazzy.itermcolors && open /tmp/Snazzy.itermcolors)

# --- Oh My Zsh ---
if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
  log "Installing Oh My Zsh..."
  RUNZSH=no KEEP_ZSHRC=yes \
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
else
  log "Oh My Zsh already installed."
fi

ZSH_CUSTOM=${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}

# --- fzf-tab (not in Homebrew, clone manually) ---
log "Installing fzf-tab plugin..."
if [[ ! -d "$ZSH_CUSTOM/plugins/fzf-tab" ]]; then
  git clone https://github.com/Aloxaf/fzf-tab "$ZSH_CUSTOM/plugins/fzf-tab"
fi

# --- fzf shell integration ---
log "Configuring fzf..."
if [[ -d "$(brew --prefix)/opt/fzf" ]]; then
  yes | "$(brew --prefix)/opt/fzf/install" --key-bindings --completion --no-update-rc
fi

# --- NVM ---
if [[ ! -d "$HOME/.nvm" ]]; then
  log "Installing NVM..."
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
else
  log "NVM already installed."
fi

# --- .zshrc ---
log "Updating ~/.zshrc..."

ZSHRC="$HOME/.zshrc"
touch "$ZSHRC"

cat << 'EOF' >> "$ZSHRC"

# ===== Custom terminal setup (generated by setup.sh) =====
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="af-magic"
plugins=(git)
source $ZSH/oh-my-zsh.sh

# Powerlevel10k (sourced directly; overrides ZSH_THEME at runtime)
source "$(brew --prefix)/opt/powerlevel10k/share/powerlevel10k/powerlevel10k.zsh-theme"

# Plugins (sourced directly from Homebrew)
source "$(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
source "$(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
source "$(brew --prefix)/share/zsh-history-substring-search/zsh-history-substring-search.zsh"

# fzf-tab
source "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/fzf-tab/fzf-tab.plugin.zsh"

# fzf shell integration
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Homebrew PATH
export PATH="/usr/local/bin:/opt/homebrew/bin:$PATH"

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# Aliases
alias python='python3'
alias cat='bat'
alias ls='eza'
alias ll='eza -l'
alias la='eza -la'

# Powerlevel10k config (run `p10k configure` to generate)
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
# ===== End custom terminal setup =====
EOF

# --- tmux.conf ---
log "Creating/updating ~/.tmux.conf..."

cat > "$HOME/.tmux.conf" << 'EOF'
setw -g mode-keys vi
set -g mouse on
EOF

log "Done! Next steps:"
echo "  1) In iTerm2, select font MesloLGS NF (Profiles → Text)."
echo "  2) Restart terminal, then run: p10k configure"
echo "  3) Start tmux with: tmux"
