#!/usr/bin/env bash
set -e

# === helper ===
log() { printf "\n\033[1;32m[INFO]\033[0m %s\n" "$*"; }
warn() { printf "\n\033[1;33m[WARN]\033[0m %s\n" "$*"; }

if [[ "$OSTYPE" != "darwin"* ]]; then
  warn "This script is designed for macOS."
  exit 1
fi

# --- Homebrew ---
if ! command -v brew >/dev/null 2>&1; then
  log "Homebrew not found. Installing..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  # add to current session environment
  if [[ -d /opt/homebrew ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
  elif [[ -d /usr/local/Homebrew ]]; then
    eval "$(/usr/local/Homebrew/bin/brew shellenv)"
  fi
else
  log "Homebrew already installed."
fi

# --- brew packages ---
log "Installing packages via Homebrew..."

brew update

brew tap homebrew/cask-fonts || true

brew list --cask iterm2 &>/dev/null || brew install --cask iterm2
brew list --cask font-meslo-lg-nerd-font &>/dev/null || brew install --cask font-meslo-lg-nerd-font

brew install zsh tmux fzf ripgrep bat fd eza git
brew install romkatv/powerlevel10k/powerlevel10k

# --- iTerm2 Snazzy theme ---
log "Downloading and opening iTerm2 Snazzy theme..."
(curl -Ls https://raw.githubusercontent.com/sindresorhus/iterm2-snazzy/main/Snazzy.itermcolors > /tmp/Snazzy.itermcolors && open /tmp/Snazzy.itermcolors)

# --- Oh My Zsh ---
if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
  log "Installing Oh My Zsh..."
  RUNZSH=no KEEP_ZSHRC=yes \
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
else
  log "Oh My Zsh already installed."
fi

ZSH_CUSTOM=${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}

# --- Zsh plugins ---
log "Installing zsh plugins..."

# zsh-autosuggestions
if [[ ! -d "$ZSH_CUSTOM/plugins/zsh-autosuggestions" ]]; then
  git clone https://github.com/zsh-users/zsh-autosuggestions \
    "$ZSH_CUSTOM/plugins/zsh-autosuggestions"
fi

# zsh-syntax-highlighting
if [[ ! -d "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting" ]]; then
  git clone https://github.com/zsh-users/zsh-syntax-highlighting \
    "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting"
fi

# fzf-tab
if [[ ! -d "$ZSH_CUSTOM/plugins/fzf-tab" ]]; then
  git clone https://github.com/Aloxaf/fzf-tab \
    "$ZSH_CUSTOM/plugins/fzf-tab"
fi

# --- fzf integration ---
log "Configuring fzf..."
if [[ -d "$(brew --prefix)/opt/fzf" ]]; then
  yes | "$(brew --prefix)/opt/fzf/install" --key-bindings --completion --no-update-rc
fi

# --- .zshrc ---
log "Updating ~/.zshrc..."

ZSHRC="$HOME/.zshrc"

# create empty file if it doesn't exist
touch "$ZSHRC"

# append configuration block at the end (between markers)
cat << 'EOF' >> "$ZSHRC"

# ===== Custom terminal setup (generated by install.sh) =====
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
  git
  zsh-autosuggestions
  fzf-tab
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# fzf integration
if [[ -d "$(brew --prefix)/opt/fzf" ]]; then
  source "$(brew --prefix)/opt/fzf/shell/key-bindings.zsh"
  source "$(brew --prefix)/opt/fzf/shell/completion.zsh"
fi

# convenient aliases
alias cat="bat"
alias ls="eza"
alias ll="eza -l"
alias la="eza -la"

# if powerlevel10k config exists
[[ -r ~/.p10k.zsh ]] && source ~/.p10k.zsh
# ===== End custom terminal setup =====
EOF

# --- tmux.conf ---
log "Creating/updating ~/.tmux.conf..."

TMUXCONF="$HOME/.tmux.conf"

cat > "$TMUXCONF" << 'EOF'
# prefix to Ctrl+a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# mouse support
set -g mouse on

# window splits
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# status bar
set -g status-bg colour234
set -g status-fg white
set -g status-left-length 40
set -g status-right-length 150
set -g status-interval 5
set -g status-left "#S "
set -g status-right "#(whoami) | %Y-%m-%d %H:%M"

set -g default-terminal "screen-256color"
EOF

log "Done! Next steps:"
echo "  1) In iTerm2, select font MesloLGS NF (Profiles → Text)."
echo "  2) Restart terminal and complete Powerlevel10k wizard."
echo "  3) Start tmux with: tmux"
